{% set name = "anarcii" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/anarcii-{{ version }}.tar.gz
  sha256: 5015fb6b5dd0c468956d13679d83d5135d6c2aaacde0bbe11e19e68c7ee07ad0

build:
  entry_points:
    - anarcii = anarcii.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - gemmi
    - msgpack-python
    - numpy
    - psutil
    - sortedcontainers
    - pytorch

test:
  imports:
    - anarcii
  commands:
    - pip check
    - anarcii --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/oxpig/ANARCII
  summary: A language model suite for numbering antigen receptor sequences.
  license: BSD-3-Clause
  license_file: LICENCE
  license_family: BSD
  license_url: https://github.com/oxpig/ANARCII/blob/main/LICENCE

extra:
  recipe-maintainers:
    - benjaminhwilliams
    - ALGW71
